export const
  RTINSPECTOR_MULTIPLE = false,
  // RTINSPECTOR_MULTIPLE = true,
  RTINSPECTOR_CAPTURE_NAME: string | null = null,
  // RTINSPECTOR_CAPTURE_NAME: string | null = 'SSR/quad',
  // RTINSPECTOR_CAPTURE_NAME: string | null = 'Greetings/intermediate0',
  // RTINSPECTOR_CAPTURE_NAME: string | null = 'main/postSwap0',
  // RTINSPECTOR_CAPTURE_NAME: string | null = 'EnvironmentMap/swap0',
  // RTINSPECTOR_CAPTURE_NAME: string | null = 'DeferredCamera/cameraTarget',
  RTINSPECTOR_CAPTURE_INDEX = 3,
  COMPONENT_UPDATE_BREAKPOINT: string | null = null,
  // COMPONENT_UPDATE_BREAKPOINT: string | null = 'lightDynamic2/shadowMapCamera',
  // COMPONENT_UPDATE_BREAKPOINT: string | null = 'lightDynamic1/shadowMapCamera',
  COMPONENT_DRAW_BREAKPOINT: string | null = null,
  COMPONENT_UPDATE_PATTERN = /.*/,
  COMPONENT_DRAW_PATTERN = /deferred/;
